"""add_archive_columns_to_videos

Revision ID: 1ae06c5082f6
Revises: 5b08f5585b6b
Create Date: 2026-08-13 20:17:46.757143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ae06c5082f6'
down_revision: Union[str, Sequence[str], None] = '5b08f5585b6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('videos', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'archived_at')
    op.drop_column('videos', 'is_archived')
    # ### end Alembic commands ###
