"""add_training_runs_table

Revision ID: 5b08f5585b6b
Revises: 8a721403ce86
Create Date: 2026-08-11 22:19:08.128293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b08f5585b6b'
down_revision: Union[str, Sequence[str], None] = '8a721403ce86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('real_performance_count', sa.Integer(), nullable=False),
    sa.Column('user_liked_count', sa.Integer(), nullable=False),
    sa.Column('auto_rejected_count', sa.Integer(), nullable=False),
    sa.Column('val_mae', sa.Float(), nullable=False),
    sa.Column('val_r2', sa.Float(), nullable=False),
    sa.Column('feature_importance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_file_path', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_runs')
    # ### end Alembic commands ###
