"""add_label_source_to_candidates

Revision ID: 8a721403ce86
Revises: d2686df969ba
Create Date: 2026-08-11 20:14:55.524543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a721403ce86'
down_revision: Union[str, Sequence[str], None] = 'd2686df969ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('label_source', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'label_source')
    # ### end Alembic commands ###
