"""add_job_type_actual_score_is_training_example

Revision ID: d2686df969ba
Revises: 19afac963f44
Create Date: 2026-08-11 20:05:09.956946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2686df969ba'
down_revision: Union[str, Sequence[str], None] = '19afac963f44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('actual_score', sa.Float(), nullable=True))
    op.add_column('candidates', sa.Column('is_training_example', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('jobs', sa.Column('job_type', sa.Text(), nullable=False, server_default=sa.text("'discovery'")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'job_type')
    op.drop_column('candidates', 'is_training_example')
    op.drop_column('candidates', 'actual_score')
    # ### end Alembic commands ###
