"""Translations EN/ID utk UI.

Struktur: TRANSLATIONS[lang][key]. "en" adalah sumber (default server), "id"
diisi dari terjemahan. Missing key di "id" jatuh ke "en" (tidak pernah kosong).

Akses di template: `{{ t("nav.dashboard") }}` — t disuntik via AppTemplates
di app/core/jinja.py.
"""

from typing import Callable

TRANSLATIONS: dict[str, dict[str, str]] = {
    # English = sumber. Semua key wajib ada di sini.
    "en": {
        # Nav / base
        "nav.dashboard": "Dashboard",
        "nav.upload": "Upload",
        "nav.candidates": "Candidates",
        "nav.history": "History",
        "nav.training": "Training",
        "nav.storage": "Storage",
        "nav.settings": "Settings",
        "nav.langLabel": "Language",
        "nav.themeLabel": "Theme",
        "nav.light": "Light",
        "nav.dark": "Dark",
        "nav.footerLegal": "Privacy Policy",
        "nav.footerTerms": "Terms of Service",

        # Settings page
        "settings.title": "Settings",
        "settings.subtitle": "Preferences aplikasi — bahasa & tema.",
        "settings.language": "Language",
        "settings.languageDesc": "Bahasa antarmuka seluruh website.",
        "settings.theme": "Theme",
        "settings.themeDesc": "Warna template aplikasi.",
        "settings.save": "Save Preferences",
        "settings.saved": "Preferences saved.",
        "settings.english": "English",
        "settings.indonesian": "Indonesia",

        # Dashboard
        "dash.totalVideos": "Total Videos",
        "dash.jobsCompleted": "Jobs Completed",
        "dash.clipsGenerated": "Clips Generated",
        "dash.pendingJobs": "Pending Jobs",
        "dash.quickActions": "Quick Actions",
        "dash.uploadDownload": "Upload / Download",
        "dash.jobHistory": "Job History",
        "dash.settings": "Settings",
        "dash.recentActivity": "Recent Activity",
        "dash.time": "Time",
        "dash.action": "Action",
        "dash.details": "Details",
        "dash.noRecent": "No recent activity",
        "dash.statusError": "Halaman dashboard gagal dimuat.",

        # Upload
        "upload.title": "Upload / Download Video",
        "upload.uploadTab": "Upload File Video",
        "upload.uploadDesc": "Pilih file video lokal dari komputer Anda.",
        "upload.allowedExt": "Pilih file video ({{ allowed_extensions | join(', ') }})",
        "upload.maxSize": "Maksimal ukuran file: {{ max_size_mb }} MB.",
        "upload.uploadBtn": "Upload Video",
        "upload.downloadTab": "Download dari URL",
        "upload.urlDesc": "Masukkan link URL video (YouTube, TikTok, dll).",
        "upload.urlLabel": "URL Video",
        "upload.urlNote": "Video akan di-download secara otomatis dan di-import.",
        "upload.downloading": "⬇ Sedang mengunduh video... (bisa memakan beberapa menit)",
        "upload.dontClose": "Jangan tutup halaman ini selama proses download berlangsung.",
        "upload.downloadBtn": "Download & Import",
        "upload.pipeline": "Pengaturan Pipeline",
        "upload.langLabel": "Bahasa",
        "upload.autoDetect": "Auto Detect",
        "upload.indonesia": "Indonesia",
        "upload.english": "English",
        "upload.clipStyle": "Clip Style (Kategori)",
        "upload.selectCategory": "— Pilih kategori —",
        "upload.numClips": "Jumlah Clip",
        "upload.cancel": "Cancel",
        "upload.jsNeedFile": "Pilih file video terlebih dahulu.",
        "upload.jsFailStart": "Gagal memulai upload.",
        "upload.jsFailUpload": "Gagal mengunggah file.",
        "upload.jsConn": "Koneksi bermasalah atau proses dihentikan.",
        "upload.jsCancel": "Membatalkan...",
        "upload.jsCancelFail": "Gagal cancel job.",
        "upload.jsReProcess": "Video sudah pernah diproses. Proses ulang?",
        "upload.jsStarting": "Memulai...",
        "upload.jsFailProcess": "Gagal memulai proses.",
        "upload.jsSystemError": "Terjadi kesalahan sistem.",
        "upload.jsNeedCategory": "Pilih kategori dulu sebelum memproses video.",
        "upload.jsNeedNumClips": "Isi jumlah clip (minimal 1) sebelum memproses video.",
        "upload.jsFailDelete": "Gagal menghapus.",
        "upload.jsUrlEmpty": "URL tidak boleh kosong.",
        "upload.jsFailDownload": "Gagal memulai download.",
        "upload.jsDownloading": "Mendownload...",
        "upload.jsTimeout": "Timeout — cek tabel video, mungkin sudah selesai.",
        "upload.jsDone": "Selesai — cek tabel video.",
        "upload.pipelineDesc": "Parameter ini dipakai saat tombol Proses di tabel video diklik.",
        "upload.minDuration": "Durasi Min (detik)",
        "upload.maxDuration": "Durasi Maks (detik)",
        "upload.keywordBoost": "Keyword Boost (koma)",
        "upload.skipKeywords": "Skip Keywords (koma)",
        "upload.videoTable": "Video Terupload",
        "upload.uploading": "Uploading...",
        "upload.fileName": "Nama File",
        "upload.status": "Status",
        "upload.type": "Tipe",
        "upload.duration": "Durasi",
        "upload.action": "Aksi",
        "upload.noVideo": "Belum ada video.",
        "upload.noCategoryWarning": "Belum ada kategori yang dibuat.",
        "upload.goToTraining": "Buat kategori di menu Training",
        "upload.defaultScoringNote": "Proses tetap bisa berjalan menggunakan scoring default (weighted-sum).",
        "upload.categoryNotTrained": "★ Kategori ini belum dilatih — akan pakai scoring default (weighted-sum).",
        "upload.categoryTrained": "✓ Kategori ini sudah dilatih — akan pakai model terlatih.",

        # Candidates list
        "cand.title": "Candidate Clips",
        "cand.empty": "Belum ada candidates.",
        "cand.click": "Klik",
        "cand.process": "Proses",
        "cand.upload": "Upload",
        "cand.archived_title": "Candidate Video Terarsip",
        "cand.archived_subtitle": "Master video sudah dihapus dari storage, tapi data candidate & training tetap tersimpan.",
        "cand.view_archive": "Lihat Arsip",
        "cand.back_to_active": "Kembali ke Candidate Aktif",
        "cand.archived_empty": "Belum ada video yang diarsipkan.",

        # Candidate detail / edit
        "candDetail.scoreBreakdown": "Score Breakdown",
        "candDetail.scoreDesc": "Kontribusi tiap analyzer ke final score (bobot × skor).",
        "candDetail.analyzer": "Analyzer",
        "candDetail.score": "Score",
        "candDetail.weight": "Bobot",
        "candDetail.contribution": "Kontribusi",
        "candDetail.reason": "Alasan",
        "candDetail.noBreakdown": "Belum ada breakdown score.",
        "candDetail.previewJson": "Preview JSON",
        "candDetail.renderClip": "Edit Video",
        "candDetail.openClip": "Open Clip",
        "candDetail.editClip": "Edit Clip (Opsional, Sebelum Upload)",
        "candDetail.text": "Text",
        "candDetail.crop": "Crop",
        "candDetail.sound": "Sound",
        "candDetail.top": "Atas",
        "candDetail.middle": "Tengah",
        "candDetail.bottom": "Bawah",
        "candDetail.addText": "Tambah Text",
        "candDetail.trimDesc": "Trim video berdasarkan waktu (dalam detik).",
        "candDetail.startSec": "Start (detik)",
        "candDetail.endSec": "End (detik)",
        "candDetail.applyTrim": "Terapkan Trim",
        "candDetail.volumeTitle": "Edit Volume Suara Asli",
        "candDetail.volume": "Volume (0–2)",
        "candDetail.applyVolume": "Terapkan Volume",
        "candDetail.addAudio": "Tambah Audio",
        "candDetail.audioFile": "File Audio",
        "candDetail.audioStart": "Mulai di detik ke",
        "candDetail.volOrig": "Vol. asli di luar range audio (0–2)",
        "candDetail.volOrigDuring": "Vol. asli saat audio tambahan (0–2)",
        "candDetail.volExtra": "Vol. audio tambahan (0–2)",
        "candDetail.subtitle": "Subtitle",
        "candDetail.format": "Format",
        "candDetail.srt": "SRT",
        "candDetail.vtt": "VTT",
        "candDetail.style": "Style",
        "candDetail.minimal": "Minimal",
        "candDetail.tiktok": "TikTok",
        "candDetail.youtube": "YouTube",
        "candDetail.langLabel": "Bahasa",
        "candDetail.genSub": "Generate & Tempel Subtitle",
        "candDetail.processing": "Memproses... 0%",
        "candDetail.processingSub": "Memproses subtitle...",
        "candDetail.error": "Terjadi kesalahan. Coba lagi.",
        "candDetail.watermark": "Watermark",
        "candDetail.watermarkDesc": "Tempel watermark wajib komunitas ke clip ini.",
        "candDetail.watermarkPosition": "Posisi",
        "candDetail.topLeft": "Kiri Atas",
        "candDetail.topRight": "Kanan Atas",
        "candDetail.bottomLeft": "Kiri Bawah",
        "candDetail.bottomRight": "Kanan Bawah",
        "candDetail.center": "Tengah",
        "candDetail.watermarkTop": "Atas (tengah)",
        "candDetail.watermarkBottom": "Bawah (tengah)",
        "candDetail.watermarkRight": "Kanan",
        "candDetail.watermarkTopRight": "Kanan (atas)",
        "candDetail.watermarkBottomRight": "Kanan (bawah)",
        "candDetail.watermarkLeft": "Kiri",
        "candDetail.watermarkTopLeft": "Kiri (atas)",
        "candDetail.watermarkBottomLeft": "Kiri (bawah)",
        "candDetail.watermarkSize": "Ukuran (% lebar video)",
        "candDetail.watermarkOpacity": "Opacity",
        "candDetail.applyWatermark": "Tempel Watermark",
        "candDetail.uploadWatermark": "Upload Watermark (PNG)",
        "candDetail.uploadWatermarkDesc": "Ganti file watermark global (dipakai semua clip).",
        "candDetail.watermarkUploaded": "Watermark baru disimpan.",
        "candDetail.watermarkUploadFail": "Gagal upload watermark.",

        # Auto Hook tab
        "candDetail.hookTab": "Hook",
        "candDetail.hookCaption": "Caption hook",
        "candDetail.hookMoment": "Momen hook",
        "candDetail.hookConfidence": "Confidence",
        "candDetail.hookApplied": "Hook diterapkan",
        "candDetail.hookSkipped": "Hook di-skip",
        "candDetail.hookNotFound": "Auto hook akan dicari otomatis saat clip di-generate.",
        "candDetail.hookLlmLoading": "Memuat status LLM...",
        "candDetail.retryHook": "Generate Ulang Hook",

        # History
        "hist.title": "Riwayat & Log Audit",
        "hist.subtitle": "Log proses aktivitas global dari system auto clipper.",
        "hist.date": "Tanggal & Waktu",
        "hist.action": "Action",
        "hist.desc": "Deskripsi",
        "hist.videoId": "ID Video",
        "hist.jobId": "ID Job",
        "hist.empty": "Belum ada riwayat aktivitas.",

        # Job detail
        "job.cancel": "Cancel Job",
        "job.steps": "Step Pipeline",
        "job.step": "Step",
        "job.status": "Status",
        "job.start": "Mulai",
        "job.end": "Selesai",
        "job.duration": "Durasi",
        "job.error": "Error",
        "job.noSteps": "Belum ada step tercatat.",

        # Storage
        "storage.title": "Storage Dashboard",
        "storage.desc": "Ringkasan penggunaan disk dan daftar video yang bisa diarsipkan.",
        "storage.uploads": "Video mentah (uploads)",
        "storage.outputs": "Clip hasil render (outputs)",
        "storage.cache": "Cache sementara",
        "storage.models": "Model training",
        "storage.filename": "Nama File",
        "storage.size": "Ukuran",
        "storage.notRendered": "Candidate belum di-render",
        "storage.allRendered": "Semua sudah di-render",
        "storage.empty": "Tidak ada video yang perlu diarsipkan.",

        # Training
        "train.category": "Kategori",
        "train.title": "Training Dashboard",
        "train.desc": "Ringkasan data training yang terkumpul dan riwayat model.",
        "train.bulkImport": "Bulk CSV Import",
        "train.dataTitle": "Data Training",
        "train.total": "Total:",
        "train.realPerf": "real_performance",
        "train.viewsLikes": "Views/likes nyata",
        "train.userLiked": "user_liked",
        "train.fromCategory": "Dari dropdown kategori",
        "train.notEnough": "Data belum cukup.",
        "train.trainBtn": "Train Model",
        "train.trainDesc": "Latih model scoring dari semua data training. Setiap klik menghasilkan run baru.",
        "train.activeModel": "Model Aktif",
        "train.run": "Run",
        "train.samples": "Samples",
        "train.valMAE": "Val MAE",
        "train.valR2": "Val R²",
        "train.noModel": "Belum ada model yang dilatih.",
        "train.history": "Riwayat Training",
        "train.historyDesc": "Klik \"Aktifkan\" untuk rollback ke model dari run tertentu.",
        "train.date": "Tanggal",
        "train.sample": "Sample",
        "train.mae": "MAE",
        "train.r2": "R²",
        "train.source": "Sumber Data",
        "train.active": "Aktif",
        "train.activate": "Aktifkan",
        "train.noHistory": "Belum ada riwayat training.",
        "train.sorted": "Diurutkan descending.",
        "train.feature": "Feature",
        "train.importance": "Importance",
        "train.visual": "Visual",
        "train.error": "Terjadi kesalahan.",

        # Training import page
        "trainImport.title": "Bulk Training Import",
        "trainImport.formatCsv": "Format CSV",
        "trainImport.source": "source",
        "trainImport.actualScore": "actual_score",
        "trainImport.optional": "boleh ada atau tidak",
        "trainImport.columns": "Kolom",
        "trainImport.content": "Isi",
        "trainImport.example": "Contoh",
        "trainImport.sourceDesc": "Path file lokal",
        "trainImport.or": "atau",
        "trainImport.actualScoreDesc": "Skor performa nyata",
        "trainImport.exampleContent": "Contoh isi file CSV:",
        "trainImport.tips": "Tips:",
        "trainImport.category": "Kategori",
        "trainImport.csvFile": "File CSV",
        "trainImport.csvFormat": "Format: .csv — maks beberapa ratus baris per upload.",
        "trainImport.progressHere": "Progress import akan muncul di sini",
        "trainImport.uploadLeft": "Upload file CSV di sebelah kiri untuk memulai.",
        "trainImport.restoring": "Memulihkan progress import...",
        "trainImport.noOldProgress": "Progress lama tidak ditemukan. Silakan upload ulang CSV.",
        "trainImport.processing": "Memproses CSV...",
        "trainImport.networkError": "Terjadi kesalahan jaringan. Coba lagi.",
        "trainImport.plsSelectCat": "Pilih kategori",
        "trainImport.plsSelectCategory": "Pilih kategori terlebih dahulu.",

        # Import progress soft
        "import.progressTitle": "Progress Import",
        "import.done": "selesai",
        "import.running": "berjalan",
        "import.total": "Total",
        "import.finished": "Selesai",
        "import.failed": "Gagal",
        "import.queued": "Antrian",
        "import.candidatesPage": "halaman Candidates",

        # Rating control
        "rating.cancel": "batalkan",
        "rating.tagCategory": "Tandai kategori...",
        "rating.noCategoryHint": "Belum ada kategori. Buat dulu di menu Training.",
        "rating.goToTraining": "Buka Training →",

        # Widgets
        "widget.viewDetails": "Lihat detail",
        "widget.open": "Open",
        "widget.generate": "Generate",
        "widget.detail": "Detail",
        "widget.delete": "Hapus",
        "widget.edited": "Sudah diedit",
        "widget.openClip": "Open Clip",
        "widget.uploadStatus": "Lihat di tabel video",
    },
    # Indonesia. Missing key fallback ke en (lihat make_translator).
    "id": {
        "nav.dashboard": "Beranda",
        "nav.upload": "Unggah",
        "nav.candidates": "Kandidat",
        "nav.history": "Riwayat",
        "nav.training": "Pelatihan",
        "nav.storage": "Penyimpanan",
        "nav.settings": "Pengaturan",
        "nav.footerLegal": "Kebijakan Privasi",
        "nav.footerTerms": "Ketentuan Layanan",

        "settings.english": "English",
        "settings.indonesian": "Indonesia",
        "upload.english": "English",
        "upload.indonesia": "Indonesia",
    },
}


def make_translator(lang: str) -> Callable[[str], str]:
    """Build translator function utk satu bahasa. Missing key → English."""
    table = TRANSLATIONS.get(lang, {})
    en = TRANSLATIONS["en"]

    def _get(key: str) -> str:
        # Substitusi template ringan (Jinja menghandle utk inline {{ }}; di sini
        # untuk string yang dibawa python-side). Sebagian besar dipakai langsung.
        return table.get(key) or en.get(key, key)

    return _get